name = "ivy-honor"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2023-10-30"

routes = [
  { pattern = "ivyhonor.com", custom_domain = true },
  { pattern = "www.ivyhonor.com", custom_domain = true }
]

# Enable the KV namespace for session storage if needed
# [[kv_namespaces]]
# binding = "SESSION_STORAGE"
# id = "YOUR_KV_NAMESPACE_ID" # You'll get this after creating a KV namespace in Cloudflare

# Add your environment variables
# [vars]
# PUBLIC_SUPABASE_URL = "your-supabase-url"
# PUBLIC_SUPABASE_ANON_KEY = "your-anon-key"
# Add other environment variables as needed

# Use this for local development with environment variables from .env.local
[env.local]

# Cloudflare Pages configuration
[build]
command = "npm run build"
output_dir = ".svelte-kit/cloudflare"

[site]
bucket = ".svelte-kit/cloudflare" 